import {basename, resolve} from 'path';
import {resolvePath} from '@nuxt/kit';

export const getUtils = (modulePath, options) => {
  const isJson = options.outputType === 'json';

  const getName = (autoImp) => {
    return autoImp.as ? autoImp.as.toString() : autoImp.name.toString();
  };
  const appDir = '/app/';
  const getModulePath = async() => {
    const mfPath = await resolvePath(modulePath);

    return mfPath.replace(appDir, '');
  };

  const getPaths = async(nuxt) => {

    const ext = options.outputType === 'es' ? 'mjs' : options.outputType;
    const filename = `.eslint.globals.${ext}`;
    const module = await getModulePath();
    const output = basename(nuxt.options.buildDir);
    const full = resolve(output, filename);
    const display = full.replace(appDir, '');

    const paths = {module, output, full, display, filename, dst: undefined};

    if (options.outputDir) {
      paths.dst = resolve(nuxt.options.rootDir, options.outputDir, filename);
      paths.display = paths.dst;
    }

    return paths;
  };

  const getJsonString = (imports) => {
    const globals = JSON.parse(`{${imports}}`);
    const output = {
      globals,
    };

    return () => JSON.stringify(output, null, 2);
  };
  const setupContents = (modulePath, imports) => {
    if (isJson) {
      return getJsonString(imports);
    }
    const line1 = options.outputType === 'cjs' ? 'module.exports = {' : 'export default {';

    return () => {
      const c = `/*
   This file is auto-generated by ${modulePath}
   */
  ${line1}
    globals: {
      ${imports},
    },
  };
  `;

      return c;
    };
  };

  const processAutoImports = (autoImports) => {
    const setList = new Set();

    const imports = Object.entries(autoImports)
    .map(([key, importGroup]) => {
      if (!importGroup?.length) {
        return null;
      }
      const imps = importGroup
      .map((imp) => {
        if (setList.has(imp)) {
          return null;
        }
        setList.add(imp);

        return isJson ? `"${imp}": "readonly"` : `    ${imp}: 'readonly'`;
      })
      .filter(Boolean)
      .join(',\n');

      return isJson ? imps : `    // ${key}\n${imps}`;
    })
    .filter(Boolean)
    .join(',\n');

    setList.clear();

    return imports;
  };

  return {
    getName,
    getPaths,
    setupContents,
    processAutoImports,
  };
};
