// @ts-check

import {basename, resolve} from 'path';
import {resolvePath} from '@nuxt/kit';

/**
 *
 * @param {string} modulePath
 * @param {object} options The merged options object for the module, a combination of defaults and user-defined options.
 * @return {object} functions An object containing the functions getName, getPaths and setupContents.
 *
 */
export const getUtils = (modulePath, options) => {
  const isJson = options.outputType === 'json';
  const appDir = '/app/';

  const getModulePath = async() => {
    const mfPath = await resolvePath(modulePath);

    return mfPath.replace(appDir, '');
  };

  const getJsonString = (imports) => {
    const globals = JSON.parse(`{${imports}}`);
    const output = {
      globals,
    };

    return () => JSON.stringify(output, null, 2);
  };

  const processAutoImports = (autoImports) => {
    const setList = new Set();

    const imports = Object.entries(autoImports)
    .map(([key, importGroup]) => {
      if (!importGroup?.length) {
        return null;
      }
      const imps = importGroup
      .map((imp) => {
        if (setList.has(imp)) {
          return null;
        }
        setList.add(imp);

        return isJson ? `"${imp}": "readonly"` : `    ${imp}: 'readonly'`;
      })
      .filter(Boolean)
      .join(',\n');

      return isJson ? imps : `    // ${key}\n${imps}`;
    })
    .filter(Boolean)
    .join(',\n');

    setList.clear();

    return imports;
  };

  /**
   *
   * @param {object} autoImp An autoImport as retrieved from Nuxt's context.getImports() function
   * @return {string} The name of the autoImport, as defined in either the 'as' property or the 'name' property of the autoImport.
   */
  const getName = (autoImp) => {
    return autoImp.as ? autoImp.as.toString() : autoImp.name.toString();
  };

  /**
   * @typedef Paths
   * @property {string} module The path of the module file
   * @property {string} output The path of the output directory
   * @property {string} full The full path of the file to be created
   * @property {string} display The path of the file to be created, with the app directory removed
   * @property {string | undefined} dst The explicit full path of the file to be created, used only if the outputDir option is provided
   */

  /**
   * @function getPaths
   * @desc Returns an object of paths to be used in the module
   * @param {object} nuxt The Nuxt object passed to the module
   * @return {Promise<Paths>} A Promise containing an object of paths to be used in the module
   */
  const getPaths = async(nuxt) => {
    const ext = options.outputType === 'es' ? 'mjs' : options.outputType;
    const filename = `.eslint.globals.${ext}`;
    const module = await getModulePath();
    const output = basename(nuxt.options.buildDir);
    const full = resolve(output, filename);
    const display = full.replace(appDir, '');

    const paths = {module, output, full, display, filename, dst: undefined};

    if (options.outputDir) {
      paths.dst = resolve(nuxt.options.rootDir, options.outputDir, filename);
      paths.display = paths.dst;
    }

    return paths;
  };

  /**
   * Returns a function that returns the contents of the file
   * @param {string} modulePath The path of the module file
   * @param {string} autoImports A string representing a set of key value pairs to be inserted into a file as the body of the globals object
   * @return {function} The function to be set as the getContents property of the options arg, passed to the `addTemplate` function
   */
  const setupContents = (modulePath, autoImports) => {
    const imports = processAutoImports(autoImports);

    if (isJson) {
      return getJsonString(imports);
    }

    const line1 = options.outputType === 'cjs' ? 'module.exports = {' : 'export default {';

    return () => {
      const c = `/*
   This file is auto-generated by ${modulePath}
   */
  ${line1}
    globals: {
      ${imports},
    },
  };
  `;

      return c;
    };
  };

  return {
    getName,
    getPaths,
    setupContents,
  };
};
